"""run.json + graph.json + db.json -> data.js, which scene.html loads.

A page opened from file:// cannot fetch JSON, so the recorded data is wrapped
as a script instead. Nothing here is edited or invented: every number the
video shows comes from one of these three files.
"""
import json, os
HERE = os.path.dirname(os.path.abspath(__file__))
load = lambda n: json.load(open(f"{HERE}/{n}"))
open(f"{HERE}/data.js", "w").write(
    "// Generated by make_data.py. Do not edit.\n"
    f"window.RUN = {json.dumps(load('run.json'))};\n"
    f"window.GRAPH = {json.dumps(load('graph.json'))};\n"
    f"window.DB = {json.dumps(load('db.json'))};\n")
print("wrote data.js", os.path.getsize(f"{HERE}/data.js"), "bytes")
