"""Measured narration -> scene windows -> timeline.js (read by scene.html).

The picture is timed to the voice: each scene lasts as long as its lines plus
a lead-in, the gaps between lines, a tail, and any extra hold the visuals need.
Re-run after gen_audio.py; then re-render.
"""
import json, os
HERE = os.path.dirname(os.path.abspath(__file__))
D = json.load(open(f"{HERE}/audio/durations.json"))

# (scene id, lines, lead-in, extra hold after the last line)
SCENES = [
    ("title",   ["s00"],         1.4, 0.8),
    ("context", ["s01"],         0.8, 0.6),
    ("graph",   ["s02"],         0.8, 2.2),
    ("safety",  ["s03", "s03b"], 0.8, 1.6),
    ("read",    ["s04"],         0.8, 0.8),
    ("dry",     ["s05"],         0.6, 1.0),
    ("propose", ["s06"],         0.6, 1.6),
    ("approve", ["s07"],         0.8, 2.0),
    ("apply",   ["s08"],         0.6, 2.0),
    ("map",     ["s09"],         0.8, 1.4),
    ("decline", ["s10"],         0.8, 1.2),
    ("limits",  ["s11"],         0.8, 1.2),
    ("end",     ["s12"],         0.8, 3.2),
]
BETWEEN, TAIL = 0.7, 0.6

t, scenes, lines = 0.0, [], {}
for sid, ids, lead, extra in SCENES:
    start = t
    cur = start + lead
    for i, lid in enumerate(ids):
        if i: cur += BETWEEN
        lines[lid] = {"start": round(cur, 3), "dur": D[lid]}
        cur += D[lid]
    t = round(cur + TAIL + extra, 3)
    scenes.append({"id": sid, "start": round(start, 3), "end": t})

total = t
open(f"{HERE}/timeline.js", "w").write(
    "// Generated by timeline.py from the measured narration. Do not edit.\n"
    f"window.TL = {json.dumps({'scenes': scenes, 'lines': lines, 'total': total}, indent=1)};\n")
json.dump({"scenes": scenes, "lines": lines, "total": total}, open(f"{HERE}/timeline.json", "w"), indent=1)
for s in scenes:
    print(f"{s['id']:8} {s['start']:7.2f} -> {s['end']:7.2f}  ({s['end']-s['start']:5.2f}s)")
print(f"total {total:.2f}s")
