import { z } from 'zod';

/**
 * Branded ID types.
 *
 * Every identifier in this schema is a UUID string, so nothing stops a FloorId
 * being passed where a ZoneId belongs — the compiler sees two strings. Branding
 * makes that a type error. The brand is applied by Zod rather than by a
 * hand-written intersection so the runtime schema and the static type cannot
 * drift apart.
 *
 * IDs are UUIDv7 (time-ordered) generated by the application, not by the
 * database. v4's randomness destroys B-tree index locality on high-insert
 * tables; generating in TS keeps us off a Postgres-version-specific function.
 * The SQL DEFAULT gen_random_uuid() exists only so hand-written inserts work.
 */

export const TenantId = z.string().uuid().brand<'TenantId'>();
export type TenantId = z.infer<typeof TenantId>;

export const UserId = z.string().uuid().brand<'UserId'>();
export type UserId = z.infer<typeof UserId>;

export const SessionId = z.string().uuid().brand<'SessionId'>();
export type SessionId = z.infer<typeof SessionId>;

export const ApiKeyId = z.string().uuid().brand<'ApiKeyId'>();
export type ApiKeyId = z.infer<typeof ApiKeyId>;

export const BuildingId = z.string().uuid().brand<'BuildingId'>();
export type BuildingId = z.infer<typeof BuildingId>;

export const FloorId = z.string().uuid().brand<'FloorId'>();
export type FloorId = z.infer<typeof FloorId>;

export const ZoneId = z.string().uuid().brand<'ZoneId'>();
export type ZoneId = z.infer<typeof ZoneId>;

export const EquipmentId = z.string().uuid().brand<'EquipmentId'>();
export type EquipmentId = z.infer<typeof EquipmentId>;

export const SensorId = z.string().uuid().brand<'SensorId'>();
export type SensorId = z.infer<typeof SensorId>;

export const AlertId = z.string().uuid().brand<'AlertId'>();
export type AlertId = z.infer<typeof AlertId>;

export const AlertRuleId = z.string().uuid().brand<'AlertRuleId'>();
export type AlertRuleId = z.infer<typeof AlertRuleId>;

export const SimulationRunId = z.string().uuid().brand<'SimulationRunId'>();
export type SimulationRunId = z.infer<typeof SimulationRunId>;

export const ThermalProfileId = z.string().uuid().brand<'ThermalProfileId'>();
export type ThermalProfileId = z.infer<typeof ThermalProfileId>;

export const OccupancyScheduleId = z.string().uuid().brand<'OccupancyScheduleId'>();
export type OccupancyScheduleId = z.infer<typeof OccupancyScheduleId>;

/**
 * UUIDv7: 48-bit big-endian millisecond timestamp, then a 12-bit monotonic
 * counter, then randomness (RFC 9562 method 2).
 *
 * The counter is not optional decoration. A plain timestamp-plus-random v7
 * only orders BETWEEN milliseconds — ids minted inside the same tick sort
 * randomly, and a 5,000-row telemetry batch is written well inside one tick.
 * That would reintroduce exactly the index fragmentation v7 is here to avoid.
 * The counter is seeded randomly on each new millisecond so concurrent
 * processes do not collide, with headroom left to increment.
 */
let lastMs = 0;
let counter = 0;

export function uuidv7(): string {
  const bytes = new Uint8Array(16);
  crypto.getRandomValues(bytes);

  let ms = Date.now();
  if (ms === lastMs) {
    counter++;
    if (counter > 0xfff) {
      // Counter exhausted inside one millisecond: borrow from the next.
      lastMs = ms + 1;
      ms = lastMs;
      counter = 0;
    }
  } else {
    if (ms < lastMs) ms = lastMs; // never go backwards if the clock steps back
    lastMs = ms;
    // Seed in the lower half so there is room to count up within the tick.
    counter = ((bytes[6]! & 0x07) << 8) | bytes[7]!;
  }

  const ts = BigInt(ms);
  bytes[0] = Number((ts >> 40n) & 0xffn);
  bytes[1] = Number((ts >> 32n) & 0xffn);
  bytes[2] = Number((ts >> 24n) & 0xffn);
  bytes[3] = Number((ts >> 16n) & 0xffn);
  bytes[4] = Number((ts >> 8n) & 0xffn);
  bytes[5] = Number(ts & 0xffn);

  bytes[6] = 0x70 | ((counter >> 8) & 0x0f); // version 7 + counter high nibble
  bytes[7] = counter & 0xff;                 // counter low byte
  bytes[8] = (bytes[8]! & 0x3f) | 0x80;      // RFC 4122 variant

  const hex = Array.from(bytes, (b) => b.toString(16).padStart(2, '0')).join('');
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`;
}
